name: Build & Test CI

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.version.outputs.changes }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}

      - name: Enable node
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Version command
        id: version
        run: |
          echo ::set-output name=changes::$(npx -p @changesets/cli changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.email "github.serviceaccount@wanews.com.au"
          git config user.name "SWM GitHub Service Account"
          git add -A
          git commit -m "Version packages" || echo "No changes to commit"
          git push
  build:
    runs-on: ubuntu-latest
    needs: version
    if: always() && needs.version.outputs.changes == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@wanews'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        run: |
          npm i -g pnpm
          pnpm set verify-store-integrity false
      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Lint types and code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Release packages
        uses: changesets/action@master
        with:
          publish: pnpx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
